//Income
export const GET_ALL_INCOME = 'GET_ALL_INCOME'
export const GET_ALL_INCOME_PENDING = 'GET_ALL_INCOME_PENDING'
export const GET_ALL_INCOME_FULFILLED = 'GET_ALL_INCOME_FULFILLED'
export const GET_ALL_INCOME_REJECTED = 'GET_ALL_INCOME_REJECTED'
export const GET_INCOME = 'GET_INCOME'
export const GET_INCOME_PENDING = 'GET_INCOME_PENDING'
export const GET_INCOME_FULFILLED = 'GET_INCOME_FULFILLED'
export const GET_INCOME_REJECTED = 'GET_INCOME_REJECTED'
export const SEARCH_INCOME = 'SEARCH_INCOME'
export const SEARCH_INCOME_PENDING = 'SEARCH_INCOME_PENDING'
export const SEARCH_INCOME_FULFILLED = 'SEARCH_INCOME_FULFILLED'
export const SEARCH_INCOME_REJECTED = 'SEARCH_INCOME_REJECTED'

//Investments
export const GET_ALL_INVESTMENTS = 'GET_ALL_INVESTMENTS'
export const GET_ALL_INVESTMENTS_FULFILLED = 'GET_ALL_INVESTMENTS_FULFILLED'
export const GET_INVESTMENTS = 'GET_INVESTMENTS'
export const GET_INVESTMENTS_FULFILLED = 'GET_INVESTMENTS_FULFILLED'
export const SEARCH_INVESTMENTS = 'SEARCH_INVESTMENTS'
export const SEARCH_INVESTMENTS_FULFILLED = 'SEARCH_INVESTMENTS_FULFILLED'

//Bank Account
export const GET_ALL_BANKACCOUNT = 'GET_ALL_BANKACCOUNT'
export const GET_ALL_BANKACCOUNT_FULFILLED = 'GET_ALL_BANKACCOUNT_FULFILLED'
export const SEARCH_BANKACCOUNT = 'SEARCH_BANKACCOUNT'
export const SEARCH_BANKACCOUNT_FULFILLED = 'SEARCH_BANKACCOUNT_FULFILLED'