//Income
export const GET_ALL_INCOME = 'GET_ALL_INCOME'
export const GET_ALL_INCOME_PENDING = 'GET_ALL_INCOME_PENDING'
export const GET_ALL_INCOME_FULFILLED = 'GET_ALL_INCOME_FULFILLED'
export const GET_ALL_INCOME_REJECTED = 'GET_ALL_INCOME_REJECTED'
export const GET_INCOME = 'GET_INCOME'
export const GET_INCOME_PENDING = 'GET_INCOME_PENDING'
export const GET_INCOME_FULFILLED = 'GET_INCOME_FULFILLED'
export const GET_INCOME_REJECTED = 'GET_INCOME_REJECTED'
export const SEARCH_INCOME = 'SEARCH_INCOME'
export const SEARCH_INCOME_PENDING = 'SEARCH_INCOME_PENDING'
export const SEARCH_INCOME_FULFILLED = 'SEARCH_INCOME_FULFILLED'
export const SEARCH_INCOME_REJECTED = 'SEARCH_INCOME_REJECTED'

//Investments
export const GET_ALL_INVESTMENTS = 'GET_ALL_INVESTMENTS'
export const GET_ALL_INVESTMENTS_PENDING = 'GET_ALL_INVESTMENTS_PENDING'
export const GET_ALL_INVESTMENTS_FULFILLED = 'GET_ALL_INVESTMENTS_FULFILLED'
export const GET_ALL_INVESTMENTS_REJECTED = 'GET_ALL_INVESTMENTS_REJECTED'
export const GET_INVESTMENTS = 'GET_INVESTMENTS'
export const GET_INVESTMENTS_PENDING = 'GET_INVESTMENTS_PENDING'
export const GET_INVESTMENTS_FULFILLED = 'GET_INVESTMENTS_FULFILLED'
export const GET_INVESTMENTS_REJECTED = 'GET_INVESTMENTS_REJECTED'
export const SEARCH_INVESTMENTS = 'SEARCH_INVESTMENTS'
export const SEARCH_INVESTMENTS_PENDING = 'SEARCH_INVESTMENTS_PENDING'
export const SEARCH_INVESTMENTS_FULFILLED = 'SEARCH_INVESTMENTS_FULFILLED'
export const SEARCH_INVESTMENTS_REJECTED = 'SEARCH_INVESTMENTS_REJECTED'

//Bank Account
export const GET_ALL_BANKACCOUNT = 'GET_ALL_BANKACCOUNT'
export const GET_ALL_BANKACCOUNT_PENDING = 'GET_ALL_BANKACCOUNT_PENDING'
export const GET_ALL_BANKACCOUNT_FULFILLED = 'GET_ALL_BANKACCOUNT_FULFILLED'
export const GET_ALL_BANKACCOUNT_REJECTED = 'GET_ALL_BANKACCOUNT_REJECTED'
export const SEARCH_BANKACCOUNT = 'SEARCH_BANKACCOUNT'

//Expense
export const GET_ALL_EXPENSE = 'GET_ALL_EXPENSE'
export const GET_ALL_EXPENSE_PENDING = 'GET_ALL_EXPENSE_PENDING'
export const GET_ALL_EXPENSE_FULFILLED = 'GET_ALL_EXPENSE_FULFILLED'
export const GET_ALL_EXPENSE_REJECTED = 'GET_ALL_EXPENSE_REJECTED'
export const GET_EXPENSE = 'GET_EXPENSE'
export const GET_EXPENSE_PENDING = 'GET_EXPENSE_PENDING'
export const GET_EXPENSE_FULFILLED = 'GET_EXPENSE_FULFILLED'
export const GET_EXPENSE_REJECTED = 'GET_EXPENSE_REJECTED'

export const DELETE_EXPENSE_PENDING = 'DELETE_EXPENSE_PENDING'
export const DELETE_EXPENSE_FULFILLED = 'DELETE_EXPENSE_FULFILLED'
export const DELETE_EXPENSE_REJECTED = 'DELETE_EXPENSE_REJECTED'

export const SEARCH_EXPENSE = 'SEARCH_EXPENSE'
export const SEARCH_EXPENSE_PENDING = 'SEARCH_EXPENSE_PENDING'
export const SEARCH_EXPENSE_FULFILLED = 'SEARCH_EXPENSE_FULFILLED'
export const SEARCH_EXPENSE_REJECTED = 'SEARCH_EXPENSE_REJECTED'
//Expense End


export const SEARCH_BANKACCOUNT_PENDING = 'SEARCH_BANKACCOUNT_PENDING'
export const SEARCH_BANKACCOUNT_FULFILLED = 'SEARCH_BANKACCOUNT_FULFILLED'
export const SEARCH_BANKACCOUNT_REJECTED = 'SEARCH_BANKACCOUNT_REJECTED'

